application:
  runtimeManifest:
    packages:
      aio-commerce-yotpo-app:
        license: Apache-2.0
        actions:
          yotpo-config:
            function: src/app/actions/yotpo-config/index.js
            runtime: nodejs:18
            web: "yes"
            inputs:
              LOG_LEVEL: debug
              YOTPO_API_KEY: $YOTPO_API_KEY
              ENABLE_REVIEWS_SYNC: $ENABLE_REVIEWS_SYNC
            annotations:
              require-adobe-auth: false

configSchema:
  title: 'Commerce Yotpo Integration'
  description: 'Integrate Adobe Commerce with Yotpo for reviews and loyalty.'
  properties:
    - title: 'Yotpo API Key'
      type: 'string'
      secret: true
      description: 'Enter your Yotpo API key from your Yotpo account.'
      envKey: 'YOTPO_API_KEY'
    - title: 'Enable Reviews Sync'
      type: 'boolean'
      description: 'Enable synchronization of product reviews between Commerce and Yotpo.'
      envKey: 'ENABLE_REVIEWS_SYNC'
      default: true

productDependencies:
  - code: 'COMMC'
    minVersion: '2.4.0'
    maxVersion: '2.7.0'