application:
  runtimeManifest:
    packages:
      aio-commerce-yotpo-app:
        license: Apache-2.0
        actions:
          yotpo-config:
            function: src/app/actions/yotpo-config/index.js
            runtime: nodejs:18
            web: "yes"
            inputs:
              YOTPO_API_KEY: $YOTPO_API_KEY
              ENABLE_REVIEWS_SYN: $ENABLE_REVIEWS_SYN
            annotations:
              require-adobe-auth: true
configSchema:
  title: 'Commerce Yotpo Integration'
  description: 'Configure Yotpo integration for Adobe Commerce.'
  properties:
    - title: 'Enable Review Synchronization'
      type: 'boolean'
      description: 'Enable or disable review synchronization.'
      envKey: 'ENABLE_REVIEWS_SYN'
      default: false
    - title: 'Yotpo API Key'
      type: 'string'
      description: 'Your Yotpo API key.'
      envKey: 'YOTPO_API_KEY'       
operations:
  view:
    - type: web
      impl: web
uix:
