runtimeManifest:
  packages:
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        registration:
          function: actions/registration/index.js
          runtime: nodejs:22
          web: "yes"
          annotations:
            require-adobe-auth: false
            final: true
      web:
        src: 'src/commerce-backend-ui-1/web-src'
        distProd: 'src/commerce-backend-ui-1/web-src/dist'
hooks:
  build-static: 'cd src/commerce-backend-ui-1/web-src && npm install && npm run build'