operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        registration:
          function: actions/registration/index.js
          web: "yes"
          runtime: "nodejs:22"
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        config:
          function: actions/config/index.js
          web: yes
          runtime: "nodejs:22"
          inputs:
            LOG_LEVEL: debug
            ENCRYPTION_KEY: $ENCRYPTION_KEY
            ENCRYPTION_IV: $ENCRYPTION_IV
            RUNTIME_NAMESPACE: $AIO_RUNTIME_NAMESPACE
          annotations:
            require-adobe-auth: true
            final: true
