name: Trigger Docs Deployment
on:
  release:
    types: [published]
  # push:
  #   branches: ["main"]
  #   paths:
  #     - '**.md'
  #     - '**.markdown'

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger deployment in main repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          repository: BlueAcornInc/aio-commerce-apps
          event-type: release-trigger
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "tag": "${{ github.ref_name }}",
              "release_url": "${{ github.event.head_commit.url }}",
              "package_name": "${{ github.event.repository.name }}",
              "sha": "${{ github.sha }}",
              "commit_message": "${{ github.event.head_commit.message }}"
            }